# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:39:37+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query

from models import (
    Dataset,
    Db,
    Facet,
    Investigation,
    Representation,
    SelectPostRequest,
    SolrResponse,
    Substance,
    SubstanceComposition,
    SubstanceStudy,
    SubstanceStudySummary,
    Term,
    Top,
    Type,
    Type2,
    Type6,
    Wt,
)

app = MCPProxy(
    contact={
        'email': 'support@ideaconsult.net',
        'name': "IDEAconsult's technical support",
        'url': 'https://phabricator.ideaconsult.net',
    },
    description='AMBIT REST web services [eNanoMapper profile] with free text & faceted search',
    license={
        'name': 'API available under GNU Lesser General Public License',
        'url': 'http://www.gnu.org/licenses/lgpl.html',
    },
    termsOfService='http://ambit.sf.net',
    title='eNanoMapper database',
    version='4.0.0',
    servers=[
        {
            'description': 'NanoReg2 database',
            'url': 'https://api.ideaconsult.net/nanoreg1',
        },
        {
            'description': 'caLIBRAte database',
            'url': 'https://api.ideaconsult.net/nanoreg1',
        },
        {
            'description': 'GRACIOUS database',
            'url': 'https://api.ideaconsult.net/nanoreg1',
        },
        {
            'description': 'PATROLS database',
            'url': 'https://api.ideaconsult.net/nanoreg1',
        },
        {
            'description': 'NanoInformaTIX database',
            'url': 'https://api.ideaconsult.net/nanoreg1',
        },
        {
            'description': 'RISKGONE database',
            'url': 'https://api.ideaconsult.net/nanoreg1',
        },
        {
            'description': 'Gov4Nano database',
            'url': 'https://api.ideaconsult.net/nanoreg1',
        },
    ],
)


@app.get(
    '/enm/{db}/investigation',
    description=""" Multiple studies in tabular form """,
    tags=['substance_information', 'investigation_summary', 'solr_query_interface'],
)
def get_investigation_results(
    db: Db = 'nanoreg1',
    type: Type = ...,
    search: str = ...,
    inchikey: Optional[str] = None,
    id: Optional[str] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Details of multiple studies
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/query/compound/{term}/{representation}',
    description=""" Returns compounds found """,
    tags=['chemical_structure_search', 'substance_information'],
)
def search_by_identifier(
    db: Db = 'nanoreg1',
    term: Term = ...,
    representation: Representation = ...,
    search: Optional[str] = None,
    b64search: Optional[str] = None,
    casesens: Optional[bool] = None,
    bundle_uri: Optional[str] = None,
    sameas: Optional[str] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Exact chemical structure search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/query/similarity',
    description=""" Returns similar compounds """,
    tags=['chemical_structure_search', 'substance_information'],
)
def search_by_similarity(
    db: Db = 'nanoreg1',
    search: Optional[str] = None,
    b64search: Optional[str] = None,
    type: Optional[Type2] = None,
    threshold: Optional[float] = None,
    dataset_uri: Optional[str] = None,
    filter_by_substance: Optional[bool] = Query(None, alias='filterBySubstance'),
    bundle_uri: Optional[str] = None,
    sameas: Optional[str] = None,
    mol: Optional[bool] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Exact similarity search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/query/smarts',
    description=""" Returns compounds with the specified substructure """,
    tags=['chemical_structure_search', 'substance_information', 'solr_query_interface'],
)
def search_by_smarts(
    db: Db = 'nanoreg1',
    search: Optional[str] = None,
    b64search: Optional[str] = None,
    type: Optional[Type2] = None,
    dataset_uri: Optional[str] = None,
    filter_by_substance: Optional[bool] = Query(None, alias='filterBySubstance'),
    bundle_uri: Optional[str] = None,
    sameas: Optional[str] = None,
    mol: Optional[bool] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Substructure search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/query/study',
    description=""" Returns endpoint summary """,
    tags=['solr_query_interface', 'chemical_structure_search'],
)
def get_endpoint_summary(
    db: Db = 'nanoreg1', top: Optional[Top] = None, category: Optional[str] = None
):
    """
    Search endpoint summary
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/substance',
    description=""" Returns a list of substances, according to the search criteria """,
    tags=['substance_information', 'chemical_structure_search'],
)
def get_substances(
    db: Db = 'nanoreg1',
    search: Optional[str] = None,
    type: Optional[Type6] = None,
    compound_uri: Optional[str] = None,
    bundle_uri: Optional[str] = None,
    add_dummy_substance: Optional[bool] = Query(None, alias='addDummySubstance'),
    studysummary: Optional[bool] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    List substances
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/substance/{uuid}',
    description=""" Returns substance representation """,
    tags=['substance_information', 'solr_query_interface'],
)
def get_substance_by_u_u_i_d(
    db: Db = 'nanoreg1',
    uuid: str = ...,
    property_uris__: Optional[str] = Query(None, alias='property_uris[]'),
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Get a substance
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/substance/{uuid}/composition',
    description=""" Returns substance composition """,
    tags=['substance_information', 'chemical_structure_search'],
)
def get_substance_composition(
    db: Db = 'nanoreg1',
    uuid: str = ...,
    all: Optional[bool] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Substance composition
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/substance/{uuid}/structures',
    description=""" Returns substance composition """,
    tags=['substance_information'],
)
def get_substance_structures(
    db: Db = 'nanoreg1',
    uuid: str = ...,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Get substance composition as a dataset
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/substance/{uuid}/study',
    description=""" Returns substance study representation """,
    tags=['substance_information', 'investigation_summary'],
)
def get_substance_study(
    db: Db = 'nanoreg1',
    uuid: str = ...,
    top: Optional[Top] = None,
    category: Optional[str] = None,
    property_uri: Optional[str] = None,
    property: Optional[str] = None,
    investigation_uuid: Optional[str] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    get substance study
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/enm/{db}/substance/{uuid}/studySummary',
    description=""" Study summary """,
    tags=['substance_information', 'investigation_summary'],
)
def get_substance_study_summary(
    db: Db = 'nanoreg1',
    uuid: str = ...,
    top: Optional[Top] = None,
    category: Optional[str] = None,
    property_uri: Optional[str] = None,
    property: Optional[str] = None,
    result: Optional[bool] = None,
    page: Optional[int] = None,
    pagesize: Optional[int] = None,
):
    """
    Get study summary for the substance
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/select',
    description=""" GET is simpler to use, but imposes restrictions on the complexity and the lenght of the parameters. """,
    tags=['solr_query_interface'],
)
def solrquery_get(
    q: Optional[str] = None,
    start: Optional[int] = None,
    rows: Optional[int] = None,
    wt: Optional[Wt] = 'xml',
):
    """
    Apache Solr powered search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/select',
    description=""" POST is more complex to use, but also allows for much for complex and lengthy queries. """,
    tags=['solr_query_interface'],
)
def solrquery_post(wt: Optional[Wt] = 'xml', body: SelectPostRequest = None):
    """
    Apache Solr powered search
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
