# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:39:37+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class Dataset(BaseModel):
    dataEntry: Optional[Dict[str, Any]] = None
    feature: Optional[Dict[str, Any]] = None
    model_uri: Optional[str] = None
    query: Optional[Dict[str, Any]] = None


class Facet(BaseModel):
    facet: Optional[Dict[str, Any]] = None


class Investigation(BaseModel):
    field_childDocuments_: Optional[Dict[str, Any]] = Field(
        None, alias='_childDocuments_'
    )
    assay: Optional[str] = None
    document_uuid: Optional[str] = None
    effectendpoint: Optional[str] = None
    endpoint: Optional[str] = None
    endpointcategory: Optional[str] = None
    err: Optional[float] = None
    errQualifier: Optional[str] = None
    guidance: Optional[str] = None
    investigation: Optional[str] = None
    loQualifier: Optional[str] = None
    loValue: Optional[float] = None
    name: Optional[str] = None
    owner_name: Optional[str] = None
    publicname: Optional[str] = None
    reference: Optional[str] = None
    reference_owner: Optional[str] = None
    reference_year: Optional[str] = None
    resulttype: Optional[str] = None
    s_uuid: Optional[str] = None
    studyResultType: Optional[str] = None
    substanceType: Optional[str] = None
    textValue: Optional[str] = None
    topcategory: Optional[str] = None
    type_s: Optional[str] = None
    unit: Optional[str] = None
    upQualifier: Optional[str] = None
    upValue: Optional[float] = None
    updated: Optional[str] = None


class SolrQuery(BaseModel):
    facet: Optional[str] = None
    filter: Optional[str] = None
    query: Optional[str] = None
    rows: Optional[int] = None
    sort: Optional[bool] = None
    start: Optional[int] = None


class Response(BaseModel):
    docs: Optional[List[Dict[str, Any]]] = None
    maxScore: Optional[float] = None
    numFound: Optional[int] = None
    start: Optional[int] = None


class ResponseHeader(BaseModel):
    QTime: Optional[int] = None
    params: Optional[Dict[str, Any]] = None
    status: Optional[int] = None
    zkConnected: Optional[bool] = None


class SolrResponse(BaseModel):
    response: Optional[Response] = None
    responseHeader: Optional[ResponseHeader] = None


class Substance(BaseModel):
    substance: Optional[Dict[str, Any]] = None


class SubstanceComposition(BaseModel):
    composition: Optional[Dict[str, Any]] = None
    feature: Optional[Dict[str, Any]] = None


class SubstanceStudy(BaseModel):
    study: Optional[Dict[str, Any]] = None


class SubstanceStudySummary(BaseModel):
    facet: Optional[Dict[str, Any]] = None


class Type(Enum):
    byinvestigation = 'byinvestigation'
    byassay = 'byassay'
    bysubstance = 'bysubstance'
    byprovider = 'byprovider'
    bycitation = 'bycitation'
    bystudytype = 'bystudytype'
    bystructure_inchikey = 'bystructure_inchikey'
    bystructure_smiles = 'bystructure_smiles'
    bystructure_name = 'bystructure_name'
    bysubstance_name = 'bysubstance_name'
    bysubstance_type = 'bysubstance_type'


class Db(Enum):
    calibrate = 'calibrate'
    enanomapper = 'enanomapper'
    enpra = 'enpra'
    marina = 'marina'
    nanogenotox = 'nanogenotox'
    nanoinformatix = 'nanoinformatix'
    nanoreg1 = 'nanoreg1'
    nanoreg2 = 'nanoreg2'
    nanotest = 'nanotest'


class Term(Enum):
    search = 'search'
    url = 'url'
    inchikey = 'inchikey'


class Representation(Enum):
    all = 'all'
    smiles = 'smiles'
    reach = 'reach'
    stdinchi = 'stdinchi'
    stdinchikey = 'stdinchikey'
    names = 'names'
    iupac_name = 'iupac_name'
    synonym = 'synonym'
    cas = 'cas'
    einecs = 'einecs'


class Type2(Enum):
    smiles = 'smiles'
    mol = 'mol'
    url = 'url'


class Top(Enum):
    P_CHEM = 'P-CHEM'
    ECOTOX = 'ECOTOX'
    ENV_FATE = 'ENV FATE'
    TOX = 'TOX'
    EXPOSURE = 'EXPOSURE'


class Type6(Enum):
    substancetype = 'substancetype'
    name = 'name'
    like = 'like'
    regexp = 'regexp'
    uuif = 'uuif'
    CompTox = 'CompTox'
    DOI = 'DOI'
    reliability = 'reliability'
    purposeFlag = 'purposeFlag'
    studyResultType = 'studyResultType'
    isRobustStudy = 'isRobustStudy'
    citation = 'citation'
    citationowner = 'citationowner'
    topcategory = 'topcategory'
    endpointcategory = 'endpointcategory'
    params = 'params'
    owner_name = 'owner_name'
    owner_uuid = 'owner_uuid'
    related = 'related'
    reference = 'reference'
    facet = 'facet'


class Wt(Enum):
    json = 'json'
    xml = 'xml'


class Params(BaseModel):
    fl: Optional[List[str]] = None
    rows: Optional[int] = None


class SelectPostRequest(BaseModel):
    facet: Optional[Dict[str, Any]] = None
    params: Optional[Params] = None
